---
- name: "Clone dotfiles"
  ansible.builtin.git:
    repo: 'https://github.com/Agterra/dotfiles.git'
    dest: "/home/{{ user }}/dotfiles"
- name: "Install dotfiles fedora"
  shell:
    echo "{{ user }}" && \
    cd "/home/{{ user }}/dotfiles" \
      && make install_fedora \
      && make setup
  when: target == 'fedora'
- name: "Install dotfile debian"
  shell:
    cd "/home/{{ user }}/dotfiles" \
      && make install_debian \
      && make setup
  when: target == 'debian'
