---
- name: "Clone dotfiles"
  ansible.builtin.git:
    repo: 'https://github.com/Agterra/dotfiles.git'
    dest: "{{ home }}/dotfiles"
- name: "Install dotfiles fedora"
  shell:
    cd "{{ home }}/dotfiles" \
      && make setup
  when: target == 'fedora'
- name: "Install dotfile debian"
  shell:
    cd "{{ home }}/dotfiles" \
      && make setup
  when: target == 'debian'
- name: "Install Astro NVIM"
  ansible.builtin.git:
    repo: 'https://github.com/AstroNvim/AstroNvim'
    dest: "{{ home }}/.config/nvim"
    depth: 1
- name: "Install oh-my-zsh"
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
- name: "Install powerlevel10k theme"
  ansible.builtin.git:
    repo: 'https://github.com/romkatv/powerlevel10k.git'
    dest: "${ZSH_CUSTOM:-$HOME/.oh-my-zsh/custom}/themes/powerlevel10k"
    depth: 1
